// packages/sd-angular/src/controls/common/SdButtonControl.ts
import {ChangeDetectionStrategy, Component, input, ViewEncapsulation} from "@angular/core";
import {coercionBoolean} from "../../utils/commons";

@Component({
  selector: "sd-button",
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  standalone: true,
  imports: [],
  template: `
    <button tabindex="0"
            [type]="type()"
            [disabled]="disabled()"
            [class]="buttonClass()"
            [style]="buttonStyle()">
      <ng-content></ng-content>
    </button>`,
  styles: [/* language=SCSS */ `
    @import "../../scss/variables";
    @import "../../scss/mixins";

    sd-button {
      > button {
        @include form-control-base();
        user-select: none;
        padding: var(--gap-sm) var(--gap-lg);

        background: white;
        border-color: var(--border-color-default);
        border-radius: var(--border-radius-default);

        font-weight: bold;
        text-align: center;
        cursor: pointer;

        transition: background .1s linear;

        &:hover {
          background: var(--theme-grey-lightest);
        }

        @include active-effect(true);

        &:disabled {
          background: white;
          border-color: var(--theme-grey-lighter);
          color: var(--text-trans-lighter);
          cursor: default;

          @include active-effect(false);
        }
      }

      &[sd-inset=true] > button {
        border-radius: 0;
        border: none;
        color: var(--theme-primary-default);

        &:hover {
          color: var(--theme-primary-darker);
        }

        &:disabled {
          background: white;
          border-color: var(--theme-grey-lighter);
          color: var(--text-trans-default);
          cursor: default;
        }
      }

      @each $key, $val in map-get($vars, theme) {
        &[sd-theme=#{$key}] > button {
          background: var(--theme-#{$key}-default);
          border-color: var(--theme-#{$key}-default);
          color: var(--text-trans-rev-default);

          &:hover {
            background: var(--theme-#{$key}-dark);
            border-color: var(--theme-#{$key}-dark);
            color: var(--text-trans-rev-default);
          }

          &:disabled {
            background: var(--theme-grey-lighter);
            border-color: var(--theme-grey-lighter);
            color: var(--text-trans-lighter);
            cursor: default;
          }
        }
      }

      &[sd-theme=link] > button {
        border-color: transparent;
        color: var(--theme-primary-default);

        &:hover {
          color: var(--theme-primary-darker);
        }

        &:disabled {
          border-color: transparent;
          color: var(--text-trans-lighter);
        }
      }

      @each $key, $val in map-get($vars, theme) {
        &[sd-theme=link-#{$key}] > button {
          border-color: transparent;
          color: var(--theme-#{$key}-default);

          &:hover {
            color: var(--theme-#{$key}-darker);
          }

          &:disabled {
            border-color: transparent;
            color: var(--text-trans-lighter);
          }
        }
      }

      &[sd-inline=true] > button {
        display: inline-block;
        width: auto;
        vertical-align: top;
      }

      &[sd-size=sm] > button {
        padding: var(--gap-xs) var(--gap-default);
      }

      &[sd-size=lg] > button {
        padding: var(--gap-default) var(--gap-xl);
      }

      &[disabled=true] {
        pointer-events: none;
      }
    }
  `],
  host: {
    "[attr.sd-theme]": "theme()",
    "[attr.sd-inline]": "inline()",
    "[attr.sd-size]": "size()",
    "[attr.disabled]": "disabled()",
    "[attr.sd-inset]": "inset()"
  }
})
export class SdButtonControl {
  type = input<"button" | "submit">("button");
  theme = input<"primary" | "secondary" | "info" | "success" | "warning" | "danger" | "grey" | "blue-grey"
    | "link" | "link-primary" | "link-secondary" | "link-info" | "link-success" | "link-warning" | "link-danger" | "link-grey" | "link-blue-grey">();
  inline = input(false, {transform: coercionBoolean});
  size = input<"sm" | "lg">();
  disabled = input(false, {transform: coercionBoolean});
  buttonStyle = input<string>();
  buttonClass = input<string>();
  inset = input(false, {transform: coercionBoolean});
}

// packages/sd-vue/src/controls/SdButtonControl.vue
<template>
  <div class="sd-button"
       :sd-theme="theme"
       :sd-size="size"
       :sd-inline="inline"
       :sd-inset="inset"
       :sd-invalid="isInvalid"
       @click="onClick">
    <button :type="type" :disabled="disabled">
      <slot></slot>
    </button>
    <div class="_invalid-indicator"></div>
  </div>
</template>

<script lang="ts">
  import {Component, Emit, Prop, Vue} from "vue-property-decorator";

  @Component
  export default class SdButtonControl extends Vue {
    @Prop({
      type: String,
      validator: value => ["primary", "secondary", "info", "success", "warning", "danger"].includes(value)
    })
    public theme?: "primary" | "secondary" | "info" | "success" | "warning" | "danger";

    @Prop({
      type: String,
      validator: value => ["sm", "lg"].includes(value)
    })
    public size?: "sm" | "lg";

    @Prop({
      type: String,
      default: "button",
      validator: value => ["button", "submit"].includes(value)
    })
    public type!: "button" | "submit";

    @Prop(Boolean)
    public inline?: boolean;

    @Prop(Boolean)
    public required?: boolean;

    @Prop(Boolean)
    public disabled?: boolean;

    @Prop(Boolean)
    public inset?: boolean;

    public isInvalid = false;

    @Emit()
    public click(event: MouseEvent): MouseEvent {
      return event;
    }

    public onClick(event: MouseEvent): void {
      this.click(event);
    }

    public mounted(): void {
      this._refresh();
    }

    public updated(): void {
      this._refresh();
    }

    private _refresh(): void {
      this.isInvalid = this.required === true && !(this.$el.firstChild as HTMLElement).innerText.trim();
    }
  }
</script>

<style scoped lang="scss">
  @import "../scss/presets";

  .sd-button {
    display: block;
    position: relative;

    & > button {
      @include form-control-base();

      font-weight: bold;
      background: white;
      cursor: pointer;
      color: var(--theme-primary-default);
      border-radius: 3px;

      &:hover {
        background: var(--theme-grey-lightest);
      }

      &:focus {
        outline-color: transparent;
        background: var(--theme-grey-lightest);
      }

      &:active {
        background: var(--theme-grey-lighter);
      }

      &:disabled {
        background: transparent;
        cursor: default;
        color: var(--text-color-default);
      }
    }

    @each $key, $val in map_get($root, theme) {
      &[sd-theme=#{$key}] > button {
        background: var(--theme-#{$key}-default);
        border-color: var(--theme-#{$key}-default);
        color: var(--text-reverse-color-default);

        &:hover,
        &:focus {
          background: var(--theme-#{$key}-dark);
          border-color: var(--theme-#{$key}-dark);
        }

        &:active {
          background: var(--theme-#{$key}-darker);
          border-color: var(--theme-#{$key}-darker);
        }

        &:disabled {
          background: var(--theme-grey-default);
          border-color: var(--theme-grey-default);
          cursor: default;
        }
      }
    }

    &[sd-size=sm] > button {
      padding: var(--gap-xs) var(--gap-sm);
    }

    &[sd-size=lg] > button {
      padding: var(--gap-default) var(--gap-lg);
    }

    &[sd-inline=true] {
      display: inline-block;

      > button {
        width: 100%;
      }
    }

    &[sd-invalid=true] > ._invalid-indicator {
      @include invalid-indicator();
    }

    &[sd-inset=true] {
      > button {
        border: none !important;
        box-shadow: none !important;
        border-radius: 0;
        color: var(--theme-primary-default);

        &:hover {
          background: var(--theme-grey-lightest);
        }

        &:active {
          background: var(--theme-grey-lighter);
        }

        &:disabled {
          background: transparent;
        }
      }

      @each $key, $val in get($root, theme) {
        &[sd-theme=#{$key}] > button {
          background: var(--theme-#{$key}-default);

          &:hover {
            background: var(--theme-#{$key}-dark);
          }

          &:active {
            background: var(--theme-#{$key}-darker);
          }

          &:disabled {
            background: var(--theme-grey-default);
          }
        }
      }
    }
  }
</style>
