// packages/sd-angular/src/controls/SdCardControl.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";

@Component({
  selector: "sd-card",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-content></ng-content>`,
  styles: [/* language=SCSS */ `
    @import "../../scss/mixins";
    @import "../../scss/variables-scss-arr";

    :host {
      display: block;
      background: white;
      border-radius: var(--border-radius-default);
      overflow: hidden;
      @include elevation(2);
      transition: box-shadow .1s ease-in-out;

      &:hover {
        @include elevation(6);
      }
    }
  `]
})
export class SdCardControl {
}

// packages/sd-vue/src/controls/SdCardControl.vue
<template>
  <div class="sd-card">
    <slot></slot>
  </div>
</template>

<script lang="ts">
  import {Component, Vue} from "vue-property-decorator";

  @Component
  export default class SdCardControl extends Vue {
  }
</script>

<style scoped lang="scss">
  @import "../scss/presets";

  .sd-card {
    display: block;
    background: white;
    border-radius: 2px;
    @include elevation(1);
    overflow: hidden;
  }
</style>
