// packages/sd-angular/src/modules/textfield/SdTextfieldControl.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  HostBinding,
  Input,
  Output,
  ViewChild,
  ViewEncapsulation
} from "@angular/core";
import {SdTypeValidate} from "../../commons/SdTypeValidate";
import {ISdNotifyPropertyChange, SdNotifyPropertyChange} from "../../commons/SdNotifyPropertyChange";
import {DateOnly, DateTime, Time} from "@simplysm/sd-core";

@Component({
  selector: "sd-textfield",
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <input #input
           [attr.type]="type === 'number' ? 'text' : type === 'datetime' ? 'datetime-local' : type"
           [required]="required"
           [value]="controlValue"
           [placeholder]="placeholder || ''"
           [attr.pattern]="pattern"
           [attr.sd-invalid]="getIsInvalid()"
           (input)="onInputInput($event)"
           (focus)="onFocus($event)"
           (blur)="onBlur($event)"
           [disabled]="disabled"
           [style.text-align]="type === 'number' ? 'right' : undefined"
           *ngIf="!multiline"/>
    <textarea #input
              [rows]="rows"
              [required]="required"
              [value]="controlValue"
              [placeholder]="placeholder || ''"
              [attr.pattern]="pattern"
              [attr.sd-invalid]="getIsInvalid()"
              (input)="onInputInput($event)"
              (focus)="onFocus($event)"
              (blur)="onBlur($event)"
              [disabled]="disabled"
              [style.text-align]="type === 'number' ? 'right' : undefined"
              *ngIf="multiline"></textarea>
    <div class="_invalid-indicator"></div>`,
  styles: [/* language=SCSS */ `
    @import "../../../scss/mixins";
    @import "../../../scss/variables-scss";

    sd-textfield {
      display: block;
      position: relative;

      > input,
      > textarea {
        @include form-control-base();
        background-clip: padding-box;
        border-radius: 0;
        margin: 0;

        background-color: var(--theme-secondary-lightest);
        border-color: var(--trans-color-default);
        transition: outline-color .1s linear;
        outline: 1px solid transparent;
        outline-offset: -1px;

        &::-webkit-input-placeholder {
          color: var(--text-color-lighter);
        }

        &::-webkit-outer-spin-button,
        &::-webkit-inner-spin-button {
          -webkit-appearance: none;
          margin: 0;
        }

        &::-webkit-calendar-picker-indicator {
          background: transparent;
          color: var(--text-color-default);
          cursor: pointer;
        }

        &:focus {
          outline-color: var(--theme-primary-default);
        }

        &:disabled {
          background: var(--theme-grey-lightest) !important;
          color: var(--text-color-light);
        }

        &[type='color'] {
          padding: 1px var(--gap-default) !important;
          height: calc(var(--gap-sm) * 2 + var(--font-size-default) * var(--line-height-strip) + 2px);
        }

        &[type=year],
        &[type=month],
        &[type=date],
        &[type=datetime],
        &[type=time],
        &[type=datetime-local] {
          padding: calc(var(--gap-sm) - 1px) var(--gap-default);
        }
      }

      > ._invalid-indicator {
        display: none;
      }

      > input[sd-invalid=true] + ._invalid-indicator,
      > input:invalid + ._invalid-indicator {
        @include invalid-indicator();
      }

      &[sd-inset=true] {
        height: 100%;

        > input,
        > textarea {
          display: block;
          border: none;
        }

        > textarea {
          height: 100%;
          resize: none;
        }
      }

      &[sd-inline=true] {
        display: inline-block;
      }

      &[sd-size=sm] > input,
      &[sd-size=sm] > textarea {
        padding: var(--gap-xs) var(--gap-sm);
      }

      &[sd-size=lg] > input,
      &[sd-size=lg] > textarea {
        padding: var(--gap-default) var(--gap-lg);
      }

      @each $color in $arr-theme-color {
        @each $brightness in $arr-theme-brightness {
          &.sd-text-color-#{$color}-#{$brightness} {
            > input,
            > textarea {
              color: var(--theme-#{$color}-#{$brightness}) !important;
            }
          }
        }
      }
    }
  `]
})
export class SdTextfieldControl implements ISdNotifyPropertyChange {
  @Input()
  @SdTypeValidate({
    type: String,
    includes: ["number", "text", "password", "date", "datetime", "time", "month", "year", "color", "email"],
    notnull: true
  })
  public type: "number" | "text" | "password" | "date" | "datetime" | "time" | "month" | "year" | "color" | "email" = "text";

  @Input()
  @SdTypeValidate(String)
  public placeholder?: string;

  @Input()
  @SdTypeValidate(Boolean)
  public required?: boolean;

  @Input()
  @SdTypeValidate([Number, String, DateOnly, DateTime, Time])
  public value?: number | string | DateOnly | DateTime | Time;

  @Output()
  public readonly valueChange = new EventEmitter<string | number | DateOnly | DateTime | Time | undefined>();

  @Input()
  @SdTypeValidate({type: Boolean, notnull: true})
  @SdNotifyPropertyChange()
  public focused = false;

  @Output()
  public readonly focusedChange = new EventEmitter<boolean>();

  @Input()
  @SdTypeValidate(Boolean)
  public disabled?: boolean;

  @Input()
  @SdTypeValidate(Number)
  public min?: number;

  @Input()
  @SdTypeValidate(Number)
  public step?: number;

  @Input()
  @SdTypeValidate(String)
  public pattern?: string;

  @ViewChild("input", {static: true})
  public inputElRef?: ElementRef<HTMLInputElement | HTMLTextAreaElement>;

  @Input()
  @SdTypeValidate(Boolean)
  @HostBinding("attr.sd-inset")
  public inset?: boolean;

  @Input()
  @SdTypeValidate(Boolean)
  @HostBinding("attr.sd-inline")
  public inline?: boolean;

  @Input()
  @SdTypeValidate({
    type: String,
    includes: ["sm", "lg"]
  })
  @HostBinding("attr.sd-size")
  public size?: "sm" | "lg";

  @Input()
  @SdTypeValidate(Boolean)
  public multiline?: boolean;

  @Input()
  @SdTypeValidate(Number)
  public rows?: number;

  public getIsInvalid(): boolean {
    const hasMinError = this.min !== undefined && this.value !== undefined && this.type === "number" && this.value < this.min;
    const hasStepError = this.step !== undefined && this.value !== undefined && this.type === "number" && Math.abs(Number(this.value) % this.step) >= 1;
    const hasRequiredError = this.required && (this.value === "" || this.value === undefined);
    return hasMinError || hasStepError || !!hasRequiredError;
  }

  public get controlValue(): number | string {
    return this.value === undefined ? ""
      : this.value instanceof DateTime ? this.value.toFormatString("yyyy-MM-ddTHH:mm")
        : this.value instanceof DateOnly ? ((this.type === "year" && this.value instanceof DateOnly) ? this.value.toFormatString("yyyy") : this.type === "month" ? this.value.toFormatString("yyyy-MM") : this.value.toString())
          : this.value instanceof Time ? this.value.toFormatString("HH:mm")
            : this.type === "number" && typeof this.value === "number" ? this.value.toLocaleString()
              : this.value;
  }

  public onInputInput(event: Event): void {
    const inputEl = event.target as (HTMLInputElement | HTMLTextAreaElement);
    let value;
    if (this.type === "number") {
      value = !inputEl.value ? undefined : Number(inputEl.value.replace(/,/g, ""));
    }
    else if (this.type === "year") {
      value = !inputEl.value ? undefined : inputEl.value.length === 4 ? DateOnly.parse(inputEl.value) : inputEl.value;
    }
    else if (this.type === "date" || this.type === "month") {
      value = !inputEl.value ? undefined : DateOnly.parse(inputEl.value);
    }
    else if (this.type === "datetime") {
      value = !inputEl.value ? undefined : DateTime.parse(inputEl.value);
    }
    else if (this.type === "time") {
      value = !inputEl.value ? undefined : Time.parse(inputEl.value);
    }
    else {
      value = inputEl.value;
    }

    if (this.value !== value) {
      this.value = value;
      this.valueChange.emit(this.value);
    }
  }

  public onFocus(event: Event): void {
    event.preventDefault();
    if (!this.focused) {
      this.focused = true;
      this.focusedChange.emit(this.focused);
    }
  }

  public onBlur(event: Event): void {
    event.preventDefault();
    if (this.focused) {
      this.focused = false;
      this.focusedChange.emit(false);
    }
  }

  public sdOnPropertyChange(propertyName: string, oldValue: any, newValue: any): void {
    if (propertyName === "focused" && this.inputElRef) {
      if (newValue) {
        if (document.activeElement !== this.inputElRef.nativeElement) {
          this.inputElRef.nativeElement.focus();
        }
      }
      else {
        if (document.activeElement === this.inputElRef.nativeElement) {
          this.inputElRef.nativeElement.blur();
        }
      }
    }
  }
}

// packages/sd-vue/src/controls/SdTextfieldControl.vue
<template>
  <div class="sd-textfield"
       :sd-inset="inset"
       :sd-inline="inline"
       :sd-size="size">
    <input :type="type === 'number' ? 'text' : type === 'datetime' ? 'datetime-local' : type"
           :value="inputValue"
           :required="required"
           :placeholder="placeholder || ''"
           :pattern="pattern"
           :sd-invalid="isInvalid"
           @input="onInput"
           @focus="onFocus"
           @blur="onBlur"
           :disabled="disabled"
           :style="{'text-align': type === 'number' ? 'right' : undefined}"
           v-if="!multiline"/>
    <textarea :value="inputValue"
              :required="required"
              :placeholder="placeholder || ''"
              :pattern="pattern"
              :sd-invalid="isInvalid"
              @input="onInput"
              @focus="onFocus"
              @blur="onBlur"
              :disabled="disabled"
              :style="{'text-align': type === 'number' ? 'right' : undefined}"
              v-if="multiline"></textarea>
    <div class="_invalid-indicator"></div>
  </div>
</template>

<script lang="ts">
  import {Component, Emit, Prop, Vue} from "vue-property-decorator";
  import {DateOnly, DateTime, Time} from "@simplysm/sd-core";

  @Component
  export default class SdTextfieldControl extends Vue {
    @Prop({
      type: String,
      default: "text",
      validator: value => ["number", "text", "password", "date", "datetime", "time", "month", "year", "color", "email"].includes(value)
    })
    public type!: "number" | "text" | "password" | "date" | "datetime" | "time" | "month" | "year" | "color" | "email";

    @Prop(String)
    public placeholder?: string;

    @Prop(Boolean)
    public required?: boolean;

    @Prop([Number, String, DateOnly, DateTime, Time])
    public value?: number | string | DateOnly | DateTime | Time;

    @Prop(Boolean)
    public disabled?: boolean;

    @Prop(Number)
    public min?: number;

    @Prop(Number)
    public step?: number;

    @Prop(String)
    public pattern?: string;

    @Prop(Boolean)
    public inset?: boolean;

    @Prop(Boolean)
    public inline?: boolean;

    @Prop({
      type: String,
      validator: value => ["sm", "lg"].includes(value)
    })
    public size?: "sm" | "lg";

    @Prop(Boolean)
    public multiline?: boolean;

    @Emit("update:value")
    public updateValue(val?: number | string | DateOnly | DateTime | Time): number | string | DateOnly | DateTime | Time | undefined {
      return val;
    }

    @Emit("blur")
    public blur(event: FocusEvent): FocusEvent {
      return event;
    }

    @Emit("focus")
    public focus(event: FocusEvent): FocusEvent {
      return event;
    }

    public inputValue: string | undefined = "";
    public isInvalid = false;

    public mounted(): void {
      this.$watch(
        () => [this.inputValue, this.type, this.min, this.step, this.required],
        () => {
          this.refreshIsInvalid();
          this.$forceUpdate();
        },
        {immediate: true}
      );

      this.$watch(
        () => this.value,
        () => {
          this.inputValue = this._convertToInputValue(this.value);
          this.$forceUpdate();
        },
        {immediate: true}
      );
    }

    public onInput(event: Event): void {
      const inputEl = event.target as (HTMLInputElement | HTMLTextAreaElement);

      if (this.type === "number") {
        if (inputEl.value.includes(".")) {
          const split = inputEl.value.replace(/[^0-9.]/g, "").split(".");
          const integerPart = Number(split[0]).toLocaleString();
          this.inputValue = integerPart + "." + (split[1] || "");
        }
        else {
          this.inputValue = Number(inputEl.value.replace(/[^0-9.]/g, "")).toLocaleString();
        }
      }

      const realValue = this._convertToRealValue(inputEl.value);
      this.updateValue(realValue);

      this.$forceUpdate();
    }

    public refreshIsInvalid(): void {
      const realValue = this._convertToRealValue(this.inputValue);
      const hasMinError = this.min !== undefined && realValue !== undefined && this.type === "number" && realValue < this.min;
      const hasStepError = this.step !== undefined && realValue !== undefined && this.type === "number" && Math.abs(Number(realValue) % this.step) >= 1;
      const hasRequiredError = this.required && (realValue === "" || realValue === undefined);
      this.isInvalid = hasMinError || hasStepError || !!hasRequiredError;
    }

    private _convertToRealValue(inputValue?: string): number | string | DateOnly | DateTime | Time | undefined {
      if (this.type === "number") {
        return !inputValue ? undefined : Number(inputValue.replace(/[^0-9.]/g, ""));
      }
      else if (this.type === "year") {
        return !inputValue ? undefined : inputValue.length === 4 ? DateOnly.parse(inputValue) : inputValue;
      }
      else if (this.type === "date" || this.type === "month") {
        return !inputValue ? undefined : DateOnly.parse(inputValue);
      }
      else if (this.type === "datetime") {
        return !inputValue ? undefined : DateTime.parse(inputValue);
      }
      else if (this.type === "time") {
        return !inputValue ? undefined : Time.parse(inputValue);
      }
      else {
        return inputValue;
      }
    }

    private _convertToInputValue(realValue?: number | string | DateOnly | DateTime | Time): string | undefined {
      if (realValue === undefined) {
        return "";
      }
      else if (realValue instanceof DateTime) {
        return realValue.toFormatString("yyyy-MM-ddTHH:mm");
      }
      else if (realValue instanceof DateOnly) {
        if (this.type === "year") {
          return (realValue as DateOnly).toFormatString("yyyy");
        }
        else if (this.type === "month") {
          return (realValue as DateOnly).toFormatString("yyyy-MM");
        }
        else {
          return realValue.toString();
        }
      }
      else if (realValue instanceof Time) {
        return realValue.toFormatString("HH:mm");
      }
      else if (this.type === "number" && typeof realValue === "number") {
        if (!Number.isSafeInteger(realValue)) {
          const integerPart = Math.floor(realValue);
          return integerPart.toLocaleString() + "." + realValue.toString().split(".")[1];
        }
        else {
          return realValue.toLocaleString();
        }
      }
      else {
        return realValue as string | undefined;
      }
    }

    public onFocus(event: FocusEvent): void {
      event.preventDefault();
      this.focus(event);
    }

    public onBlur(event: FocusEvent): void {
      event.preventDefault();
      this.blur(event);
    }
  }
</script>

<style scoped lang="scss">
  @import "../scss/presets";

  .sd-textfield {
    display: block;
    position: relative;

    > input,
    > textarea {
      @include form-control-base();
      background-clip: padding-box;
      border-radius: 0;
      margin: 0;

      background-color: var(--theme-secondary-lightest);
      border-color: var(--trans-color-default);
      transition: outline-color .1s linear;
      outline: 1px solid transparent;
      outline-offset: -1px;

      &::-webkit-input-placeholder {
        color: var(--text-color-lighter);
      }

      &::-webkit-outer-spin-button,
      &::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
      }

      &::-webkit-calendar-picker-indicator {
        background: transparent;
        color: var(--text-color-default);
        cursor: pointer;
      }

      &:focus {
        outline-color: var(--theme-primary-default);
      }

      &:disabled {
        background: var(--theme-grey-lightest) !important;
        color: var(--text-color-light);
      }

      &[type='color'] {
        padding: 1px var(--gap-default) !important;
        height: calc(var(--gap-sm) * 2 + var(--line-height) * var(--font-size-default) + 2);
      }

      &[type=year],
      &[type=month],
      &[type=date],
      &[type=datetime],
      &[type=time],
      &[type=datetime-local] {
        padding: calc(var(--gap-sm) - 1) var(--gap-default);
      }
    }

    > ._invalid-indicator {
      display: none;
    }

    > input[sd-invalid=true] + ._invalid-indicator,
    > input:invalid + ._invalid-indicator {
      @include invalid-indicator();
    }

    &[sd-inset=true] {
      height: 100%;

      > input,
      > textarea {
        display: block;
        border: none;
      }

      > textarea {
        height: 100%;
        resize: none;
      }
    }

    &[sd-inline=true] {
      display: inline-block;
    }

    &[sd-size=sm] > input,
    &[sd-size=sm] > textarea {
      padding: var(--gap-xs) var(--gap-sm);
    }

    &[sd-size=lg] > input,
    &[sd-size=lg] > textarea {
      padding: var(--gap-default) var(--gap-lg);
    }

    @each $key, $val in map_get($root, theme) {
      @each $key1, $val1 in $val {
        &.sd-text-color-#{$key}-#{$key1} {
          > input,
          > textarea {
            color: var(--theme-#{$key}-#{$key1}) !important;
          }
        }
      }
    }
  }
</style>
