// packages/angular/src/ui/overlay/toast/sd-toast-container.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  input,
  ViewEncapsulation,
} from "@angular/core";

@Component({
  selector: "sd-toast-container",
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  standalone: true,
  host: {
    "[attr.data-sd-overlap]": "overlap() || undefined",
  },
  template: `<ng-content />`,
  styles: [
    /* language=SCSS */ `
      @use "../../../../scss/commons/variables";
      @use "sass:map";

      sd-toast-container {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        display: flex;
        flex-direction: column;
        align-items: center;
        z-index: map.get(variables.$vars, z-index, toast);
        pointer-events: none;

        @media all and (max-width: variables.$breakpoint-mobile) {
          flex-direction: column-reverse;
        }

        &[data-sd-overlap] {
          display: block;
          bottom: 0;
          height: 100%;

          > sd-toast {
            position: absolute;
            bottom: var(--gap-xxl);
            left: var(--gap-xxl);
            right: var(--gap-xxl);
            width: auto;
            max-width: none;
          }
        }
      }
    `,
  ],
})
export class SdToastContainer {
  overlap = input(false, { transform: booleanAttribute });
}

// _back/240916_react/sd-react/src/controls/SdToastContainer.tsx
import { component } from "../utils/component";
import { omit } from "../utils/omit";
import { keys } from "@simplysm/ts-transformer-keys";
import styled, { css } from "styled-components";

interface IProps {
  $overlap: boolean;
}

export const SdToastContainer = component<IProps, "div">("SdToastContainer", (props, fwdRef) => {
  return (
    <RootDiv {...omit(props, keys<IProps>())} ref={fwdRef} $overlap={props.$overlap}>
      {props.children}
    </RootDiv>
  );
});

const RootDiv = styled.div<{
  $overlap: boolean;
}>`
  display: flex;
  flex-direction: column;
  position: fixed;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  pointer-events: none;
  padding: var(--gap-xxl);
  z-index: var(--z-index-toast);

  @media all and (max-width: 520px) {
    flex-direction: column-reverse;
  }

  ${(props) =>
    props.$overlap &&
    css`
      display: block;

      > * {
        position: absolute;
        bottom: var(--gap-xxl);
        left: var(--gap-xxl);
        right: var(--gap-xxl);
        width: auto;
      }
    `}
`;
