// packages/sd-vue/src/controls/SdBarcodeControl.vue
<template>
  <div class="sd-barcode">
    <canvas></canvas>
  </div>
</template>

<script lang="ts">
  import {Component, Prop, Vue} from "vue-property-decorator";

  // tslint:disable-next-line:no-var-requires no-require-imports
  require("jsbarcode");

  @Component
  export default class SdBarcodeControl extends Vue {
    @Prop(String)
    public value?: string;

    @Prop({
      type: String,
      default: "code128"
    })
    public type!: string;

    @Prop({
      type: Number,
      default: 1
    })
    public lineWidth!: number;

    @Prop({
      type: Number,
      default: 58
    })
    public height!: number;

    public updated(): void {
      if (this.value) {
        const canvasEl = this.$el.firstChild as HTMLCanvasElement;

        if (canvasEl) {
          window["JsBarcode"](
            canvasEl,
            this.value,
            {
              format: this.type,
              width: this.lineWidth,
              height: this.height,
              fontOptions: "bold",
              fontSize: this.lineWidth * 12
            }
          );
        }
      }
    }
  }
</script>

<style scoped lang="scss">
  @import "../scss/presets";

  .sd-barcode {
  }
</style>

// packages/sd-angular/src/modules/barcode/SdBarcodeControl.ts
import {ChangeDetectionStrategy, Component, ElementRef, Input} from "@angular/core";
import {ISdNotifyPropertyChange, SdNotifyPropertyChange} from "../../commons/SdNotifyPropertyChange";
import {SdTypeValidate} from "../../commons/SdTypeValidate";

// tslint:disable-next-line:no-var-requires no-require-imports
require("jsbarcode");

@Component({
  selector: "sd-barcode",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <canvas></canvas>`
})
export class SdBarcodeControl implements ISdNotifyPropertyChange {
  @Input()
  @SdTypeValidate(String)
  @SdNotifyPropertyChange()
  public value?: string;

  @Input()
  @SdTypeValidate(String)
  @SdNotifyPropertyChange()
  public type = "code128";

  @Input()
  @SdTypeValidate(Number)
  @SdNotifyPropertyChange()
  public lineWidth = 1;

  @Input()
  @SdTypeValidate(Number)
  @SdNotifyPropertyChange()
  public height = 58;

  public constructor(private readonly _elRef: ElementRef) {
  }

  public sdOnPropertyChange(propertyName: string, oldValue: any, newValue: any): void {
    if (newValue) {
      const canvasEl = (this._elRef.nativeElement as HTMLElement).findAll("canvas")[0];

      if (canvasEl) {
        window["JsBarcode"](
          canvasEl,
          this.value,
          {
            format: this.type,
            width: this.lineWidth,
            height: this.height,
            fontOptions: "bold",
            fontSize: this.lineWidth * 12
          }
        );
      }
    }
  }
}
