// packages/angular/src/controls/button/sd-button.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  input,
  ViewEncapsulation,
} from "@angular/core";
import { SdRipple } from "../../core/ripple/sd-ripple";

@Component({
  selector: "sd-button",
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  standalone: true,
  imports: [SdRipple],
  template: `
    <button
      tabindex="0"
      [type]="type()"
      [disabled]="disabled()"
      [class]="buttonClass()"
      [style]="buttonStyle()"
      [sdRipple]="!disabled()"
    >
      <ng-content />
    </button>
  `,
  styles: [
    /* language=SCSS */ `
      @use "sass:map";

      @use "../../../scss/commons/variables";
      @use "../../../scss/commons/mixins";

      sd-button {
        > button {
          @include mixins.form-control-base();
          user-select: none;
          padding: var(--gap-sm) var(--gap-lg);
          width: 100%;

          background: var(--control-color);
          border-color: var(--border-color-default);
          border-radius: var(--border-radius-default);

          font-weight: bold;
          text-align: center;
          cursor: pointer;

          transition: 0.1s linear;
          transition-property: border, background;

          &:hover {
            background: var(--theme-gray-lightest);
          }

          &:disabled {
            background: var(--control-color);
            border-color: var(--theme-gray-lighter);
            color: var(--text-trans-lighter);
            cursor: default;
          }
        }

        &[data-sd-inset="true"] > button {
          border-radius: 0;
          border: none;
          color: var(--theme-primary-default);

          &:hover {
            color: var(--theme-primary-darker);
          }

          &:disabled {
            background: var(--control-color);
            border-color: var(--theme-gray-lighter);
            color: var(--text-trans-default);
            cursor: default;
          }
        }

        @each $key, $val in map.get(variables.$vars, theme) {
          &[data-sd-theme="#{$key}"] > button {
            background: var(--theme-#{$key}-default);
            border-color: var(--theme-#{$key}-default);
            color: var(--text-trans-rev-default);

            &:hover {
              background: var(--theme-#{$key}-dark);
              border-color: var(--theme-#{$key}-dark);
              color: var(--text-trans-rev-default);
            }

            &:disabled {
              background: var(--theme-gray-lighter);
              border-color: var(--theme-gray-lighter);
              color: var(--text-trans-lighter);
              cursor: default;
            }
          }
        }

        &[data-sd-theme="link"] > button {
          border-color: transparent;
          background: transparent;
          color: var(--theme-primary-default);

          &:hover {
            color: var(--theme-primary-darker);
          }

          &:disabled {
            border-color: transparent;
            color: var(--text-trans-lighter);
          }
        }

        @each $key, $val in map.get(variables.$vars, theme) {
          &[data-sd-theme="link-#{$key}"] > button {
            border-color: transparent;
            background: transparent;
            color: var(--theme-#{$key}-default);

            &:hover {
              background: var(--trans-lighter);
              color: var(--theme-#{$key}-darker);
            }

            &:disabled {
              border-color: transparent;
              color: var(--text-trans-lighter);
            }
          }
        }

        &[data-sd-theme="link-rev"] > button {
          border-color: transparent;
          background: transparent;
          color: var(--text-trans-rev-default);

          &:hover {
            color: var(--text-trans-rev-dark);
          }

          &:disabled {
            border-color: transparent;
            color: var(--text-trans-rev-darker);
          }
        }

        &[data-sd-inline="true"] > button {
          display: inline-block;
          width: auto;
          vertical-align: top;
        }

        &[data-sd-size="sm"] > button {
          padding: var(--gap-xs) var(--gap-default);
        }

        &[data-sd-size="lg"] > button {
          padding: var(--gap-default) var(--gap-xl);
        }

        &[data-sd-disabled="true"] {
          &:active {
            pointer-events: none;
          }
        }
      }
    `,
  ],
  host: {
    "[attr.data-sd-theme]": "theme()",
    "[attr.data-sd-inline]": "inline()",
    "[attr.data-sd-size]": "size()",
    "[attr.data-sd-inset]": "inset()",
    "[attr.data-sd-disabled]": "disabled()",
  },
})
export class SdButton {
  type = input<"button" | "submit">("button");
  theme = input<
    | "primary"
    | "secondary"
    | "info"
    | "success"
    | "warning"
    | "danger"
    | "gray"
    | "blue-gray"
    | "link"
    | "link-primary"
    | "link-secondary"
    | "link-info"
    | "link-success"
    | "link-warning"
    | "link-danger"
    | "link-gray"
    | "link-blue-gray"
    | "link-rev"
  >();
  inline = input(false, { transform: booleanAttribute });
  inset = input(false, { transform: booleanAttribute });
  size = input<"sm" | "lg">();
  disabled = input(false, { transform: booleanAttribute });
  buttonStyle = input<string>();
  buttonClass = input<string>();
}

// _back/240919_react_포기/sd-react/src/controls/SdButton.tsx
import styled, { css } from "styled-components";
import { mixins } from "../style/mixins";
import { component, TFwdRef, TProps } from "../utils/component";
import { omit } from "../utils/omit";
import { keys } from "@simplysm/ts-transformer-keys";
import { SdBusyContainer } from "./SdBusyContainer";

export type TSdButtonTheme =
  | "primary"
  | "secondary"
  | "info"
  | "success"
  | "warning"
  | "danger"
  | "grey"
  | "blue-grey"
  | "link"
  | "link-primary"
  | "link-secondary"
  | "link-info"
  | "link-success"
  | "link-warning"
  | "link-danger"
  | "link-grey"
  | "link-blue-grey";

interface IProps {
  $theme?: TSdButtonTheme;
  $inline?: boolean;
  $inset?: boolean;
  $size?: "sm" | "lg";
}

export const SdButton = component("SdButton", (props: TProps<IProps, "button">, fwdRef: TFwdRef<"button">) => {
  return (
    <>
      <SdBusyContainer></SdBusyContainer>
      <RootButton
        {...omit(props, keys<IProps>())}
        ref={fwdRef}
        $theme={props.$theme}
        $inline={props.$inline}
        $inset={props.$inset}
        $size={props.$size}
      >
        {props.children}
      </RootButton>
    </>
  );
});

const RootButton = styled.button<{
  $theme:
    | "primary"
    | "secondary"
    | "info"
    | "success"
    | "warning"
    | "danger"
    | "grey"
    | "blue-grey"
    | "link"
    | "link-primary"
    | "link-secondary"
    | "link-info"
    | "link-success"
    | "link-warning"
    | "link-danger"
    | "link-grey"
    | "link-blue-grey"
    | undefined;
  $inline: boolean | undefined;
  $inset: boolean | undefined;
  $size: "sm" | "lg" | undefined;
}>`
  ${(props) => [
    css`
      font-family: var(--font-family);

      display: block;
      width: 100%;
      padding: var(--gap-sm) var(--gap-lg);
      background: white;

      font-size: var(--font-size-default);
      line-height: var(--line-height);

      border-radius: ${props.$inset ? 0 : "var(--border-radius-default)"};
      border: ${props.$inset ? "none" : "1px solid var(--border-color-default)"};
      color: var(--text-trans-default);

      user-select: none;

      font-weight: bold;
      text-align: center;
      cursor: pointer;

      transition: background 0.1s linear;

      &:hover {
        background: var(--theme-grey-lightest);
        ${
          props.$inset &&
          css`
            color: var(--theme-primary-darker);
          `
        }
      }

      ${mixins.activeEffect(true)}
      &:disabled {
        background: white;
        border-color: var(--theme-grey-lighter);
        color: var(--text-trans-lighter);
        cursor: default;

        ${mixins.activeEffect(false)}
      }

    ,
    ${
      props.$theme &&
      !props.$theme.startsWith("link") &&
      css`
        background: var(--theme-${props.$theme}-default);
        border-color: var(--theme-${props.$theme}-default);
        color: var(--text-trans-rev-default);

        &:hover {
          background: var(--theme-${props.$theme}-dark);
          border-color: var(--theme-${props.$theme}-dark);
          color: var(--text-trans-rev-default);
        }

        &:disabled {
          background: var(--theme-grey-lighter);
          border-color: var(--theme-grey-lighter);
          color: var(--text-trans-lighter);
          cursor: default;
        }
      `
    } ${
      props.$theme === "link" &&
      css`
        border-color: transparent;
        color: var(--theme-primary-default);

        &:hover {
          color: var(--theme-primary-darker);
        }

        &:disabled {
          border-color: transparent;
          color: var(--text-trans-lighter);
        }
      `
    } ${
      props.$theme &&
      props.$theme.startsWith("link") &&
      css`
        border-color: transparent;
        color: var(--theme-${props.$theme.substring(5)}-default);

        &:hover {
          color: var(--theme-${props.$theme.substring(5)}-darker);
        }

        &:disabled {
          border-color: transparent;
          color: var(--text-trans-lighter);
        }
      `
    } ${
      props.$inline &&
      css`
        display: inline-block;
        width: auto;
        vertical-align: top;
      `
    } ${
      props.$size === "sm" &&
      css`
        padding: var(--gap-xs) var(--gap-default);
      `
    } ${
      props.$size === "lg" &&
      css`
        padding: var(--gap-default) var(--gap-xl);
      `
    } ${
      props.disabled &&
      css`
        pointer-events: none;
      `
    }
    `
  ]}
`;
