// packages/sd-angular/src/modules/toast/sd-toast.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, HostBinding, Input } from "@angular/core";
import { SdInputValidate } from "../../decorators/SdInputValidate";
import { sdThemes, TSdTheme } from "../../commons";

@Component({
  selector: "sd-toast",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="_sd-toast-block">
      <div class="_sd-toast-message">
        <ng-content></ng-content>
      </div>
      <div class="_sd-toast-progress" *ngIf="useProgress">
        <div class="_sd-toast-progress-bar" [style.width.%]="progress">
        </div>
      </div>
    </div>`,
  styles: [/* language=SCSS */ `
    @import "../../../scss/mixins";
    @import "../../../scss/variables-scss-arr";

    :host {
      display: block;
      margin-bottom: var(--gap-sm);
      text-align: center;
      width: 100%;

      > ._sd-toast-block {
        display: inline-block;
        text-align: left;
        color: white;
        transform: translateY(-100%);
        border-radius: 4px;
        opacity: 0;
        @include elevation(6);

        > ._sd-toast-message {
          padding: var(--gap-sm) var(--gap-default);
        }

        > ._sd-toast-progress {
          background: var(--theme-color-grey-default);
          height: 4px;
          border-radius: 4px;

          > ._sd-toast-progress-bar {
            height: 4px;
            transition: width 1s ease-out;
          }
        }
      }

      @each $color in $arr-theme-color {
        &[sd-theme=#{$color}] {
          > ._sd-toast-block {
            background: var(--theme-color-#{$color}-default);

            > ._sd-toast-progress {
              > ._sd-toast-progress-bar {
                background: var(--theme-color-#{$color}-default);
              }
            }
          }
        }
      }

      &[sd-open=true] {
        > ._sd-toast-block {
          transform: none;
          transition: .1s ease-out;
          transition-property: transform, opacity;
          opacity: 1;
        }
      }

      &[sd-open=false] {
        > ._sd-toast-block {
          transform: translateY(-100%);
          transition: .1s ease-in;
          transition-property: transform, opacity;
          opacity: 0;
        }
      }

      @media screen and (max-width: 520px) {
        > ._sd-toast-block {
          @include elevation(0);
          border-radius: calc(var(--line-height) / 2);

          transform: translateY(100%);

          > ._sd-toast-message {
            padding: var(--gap-xs) var(--gap-default);
          }
        }

        &[sd-open=false] {
          > ._sd-toast-block {
            transform: translateY(100%);
          }
        }
      }
    }
  `]
})
export class SdToastComponent {
  @Input()
  @SdInputValidate(Boolean)
  @HostBinding("attr.sd-open")
  public open?: boolean;

  @Input()
  @SdInputValidate(Boolean)
  public useProgress?: boolean;

  @Input()
  @SdInputValidate(Number)
  public progress?: number;

  public close = new EventEmitter<any>();

  @Input()
  @SdInputValidate({
    type: String,
    notnull: true,
    includes: sdThemes
  })
  @HostBinding("attr.sd-theme")
  public theme?: TSdTheme = "info";
}

// _back/240919_react_포기/sd-react/src/controls/SdToast.tsx
import { component, TFwdRef, TProps } from "../utils/component";
import styled, { css, keyframes } from "styled-components";
import { omit } from "../utils/omit";
import { keys } from "@simplysm/ts-transformer-keys";
import { mixins } from "../style/mixins";
import { variables } from "../style/variables";

export type TSdToastTheme = "info" | "success" | "warning" | "danger";

interface IProps {
  $progress?: number;
  $theme?: TSdToastTheme;
  $closing?: boolean;
}

export const SdToast = component("SdToast", (props: TProps<IProps, "div">, fwdRef: TFwdRef<"div">) => {
  return (
    <RootDiv
      {...omit(props, keys<IProps>())}
      ref={fwdRef}
      $progress={props.$progress}
      $theme={props.$theme ?? "info"}
      $closing={props.$closing ?? false}
    >
      <div className={"_sd-toast-block"}>
        <div className={"_sd-toast-message"}>{props.children}</div>
        {props.$progress != null && (
          <div className={"_sd-toast-progress"}>
            <div className={"_sd-toast-progress-bar"}></div>
          </div>
        )}
      </div>
    </RootDiv>
  );
});

const RootDiv = styled.div<{
  $progress: number | undefined;
  $theme: TSdToastTheme;
  $closing: boolean;
}>`
  ${props => css`
    display: block;
    margin-bottom: var(--gap-sm);
    text-align: center;
    width: 100%;
    pointer-events: none;

    > ._sd-toast-block {
      display: inline-block;
      text-align: left;
      color: white;
      border-radius: var(--border-radius-lg);
      ${mixins.elevation(12)}
      pointer-events: auto;

      transform: none;
      opacity: 1;
      animation: ${kfOpen(false)} 0.1s ease-out;

      ${props.$closing && css`
        transform: translateY(-100%);
        transition: 0.1s ease-in;
        transition-property: transform, opacity;
        opacity: 0;
      `};

      > ._sd-toast-message {
        padding: var(--gap-default) var(--gap-lg);
      }

      ${props.$progress != null && css`
        > ._sd-toast-progress {
          background: var(--theme-grey-default);
          height: 4px;
          border-radius: var(--border-radius-xl);
          margin: 0 4px 4px 4px;

          > ._sd-toast-progress-bar {
            border-radius: var(--border-radius-xl);
            height: 4px;
            transition: width 1s ease-out;
            width: ${props.$progress}%;
          }
        }`
      }
    }

    ${Object.keys(variables.theme).map(
      (key) => css`
        > ._sd-toast-block {
          background: var(--theme-${key}-default);

          > ._sd-toast-progress {
            background: var(--theme-${key}-darker);

            > ._sd-toast-progress-bar {
              background: var(--theme-${key}-lighter);
            }
          }
        }
      `
    )};

    @media (max-width: 520px) {
      ${kfOpen(true)}
      > ._sd-toast-block {
        border-radius: calc(var(--line-height) / 2);

        > ._sd-toast-message {
          padding: var(--gap-xs) var(--gap-default);
        }
      }
    }
  `}
`;

const kfOpen = (bottom: boolean) => keyframes`
  from {
    transform: translateY(${bottom ? "100%" : "-100%"});
    opacity: 0;
  }
  to {
    transform: none;
    opacity: 1;
  }
`;
