// packages/sd-vue/src/controls/SdButtonControl.vue
<template>
  <div class="sd-button"
       :sd-theme="theme"
       :sd-size="size"
       :sd-inline="inline"
       :sd-inset="inset"
       :sd-invalid="isInvalid"
       @click="onClick">
    <button :type="type" :disabled="disabled">
      <slot></slot>
    </button>
    <div class="_invalid-indicator"></div>
  </div>
</template>

<script lang="ts">
  import {Component, Emit, Prop, Vue} from "vue-property-decorator";

  @Component
  export default class SdButtonControl extends Vue {
    @Prop({
      type: String,
      validator: value => ["primary", "secondary", "info", "success", "warning", "danger"].includes(value)
    })
    public theme?: "primary" | "secondary" | "info" | "success" | "warning" | "danger";

    @Prop({
      type: String,
      validator: value => ["sm", "lg"].includes(value)
    })
    public size?: "sm" | "lg";

    @Prop({
      type: String,
      default: "button",
      validator: value => ["button", "submit"].includes(value)
    })
    public type!: "button" | "submit";

    @Prop(Boolean)
    public inline?: boolean;

    @Prop(Boolean)
    public required?: boolean;

    @Prop(Boolean)
    public disabled?: boolean;

    @Prop(Boolean)
    public inset?: boolean;

    @Emit()
    public click(event: MouseEvent): MouseEvent {
      return event;
    }

    public isInvalid = false;

    public onClick(event: MouseEvent): void {
      this.click(event);
    }

    public mounted(): void {
      this._refresh();
    }

    public updated(): void {
      this._refresh();
    }

    private _refresh(): void {
      this.isInvalid = this.required === true && !(this.$el.firstChild as HTMLElement).innerText.trim();
    }
  }
</script>

<style scoped lang="scss">
  @import "../scss/presets";

  .sd-button {
    display: block;
    position: relative;

    > button {
      @include form-control-base();

      font-weight: bold;
      background: white;
      cursor: pointer;
      color: var(--theme-primary-default);
      border-radius: 3px;

      &:hover {
        background: var(--theme-grey-lightest);
      }

      &:focus {
        outline-color: transparent;
        background: var(--theme-grey-lightest);
      }

      &:active {
        background: var(--theme-grey-lighter);
      }

      &:disabled {
        background: transparent;
        cursor: default;
        color: var(--text-color-default);
      }
    }

    @each $key, $val in map_get($root, theme) {
      &[sd-theme=#{$key}] > button {
        background: var(--theme-#{$key}-default);
        border-color: var(--theme-#{$key}-default);
        color: var(--text-reverse-color-default);

        &:hover,
        &:focus {
          background: var(--theme-#{$key}-dark);
          border-color: var(--theme-#{$key}-dark);
        }

        &:active {
          background: var(--theme-#{$key}-darker);
          border-color: var(--theme-#{$key}-darker);
        }

        &:disabled {
          background: var(--theme-grey-default);
          border-color: var(--theme-grey-default);
          cursor: default;
        }
      }
    }

    &[sd-size=sm] > button {
      padding: var(--gap-xs) var(--gap-sm);
    }

    &[sd-size=lg] > button {
      padding: var(--gap-default) var(--gap-lg);
    }

    &[sd-inline=true] {
      display: inline-block;

      > button {
        width: 100%;
      }
    }

    &[sd-invalid=true] > ._invalid-indicator {
      @include invalid-indicator();
    }

    &[sd-inset=true] {
      > button {
        border: none !important;
        box-shadow: none !important;
        border-radius: 0;
        color: var(--theme-primary-default);

        &:hover {
          background: var(--theme-grey-lightest);
        }

        &:active {
          background: var(--theme-grey-lighter);
        }

        &:disabled {
          background: transparent;
        }
      }

      @each $key, $val in map_get($root, theme) {
        &[sd-theme=#{$key}] > button {
          background: var(--theme-#{$key}-default);

          &:hover {
            background: var(--theme-#{$key}-dark);
          }

          &:active {
            background: var(--theme-#{$key}-darker);
          }

          &:disabled {
            background: var(--theme-grey-default);
          }
        }
      }
    }
  }
</style>

// packages/sd-angular/src/controls/SdButtonControl.ts
import { ChangeDetectionStrategy, Component, HostBinding, Input } from "@angular/core";
import { SdInputValidate } from "../decorators/SdInputValidate";
import { DomSanitizer, SafeHtml } from "@angular/platform-browser";

@Component({
  selector: "sd-button",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button tabindex="0"
            [attr.type]="type"
            [disabled]="disabled"
            [attr.class]="safeHtml(buttonClass)"
            [attr.style]="safeHtml(buttonStyle)">
      <ng-content></ng-content>
    </button>`,
  styles: [/* language=SCSS */ `
    @import "../../scss/mixins";
    @import "../../scss/variables-scss-arr";

    :host {
      > button {
        @include form-control-base();
        padding: var(--gap-sm) var(--gap-lg);

        background: white;
        border-color: var(--sd-border-color);
        border-radius: 2px;

        font-weight: bold;
        text-align: center;
        cursor: pointer;

        &:hover {
          background: var(--theme-color-grey-lightest);
        }

        &:active {
          background: var(--theme-color-grey-lighter);
        }

        &:disabled {
          background: white;
          border-color: var(--theme-color-grey-lighter);
          color: var(--text-brightness-lighter);
          cursor: default;
        }
      }

      &[sd-inset] > button {
        border-radius: 0;
        border: none;
        color: var(--theme-color-primary-default);

        &:hover {
          color: var(--theme-color-primary-darker);
        }

        &:disabled {
          background: white;
          border-color: var(--theme-color-grey-lighter);
          //color: var(--text-brightness-lighter);
          color: var(--text-brightness-default);
          cursor: default;
        }
      }

      @each $theme in $arr-theme-color {
        &[sd-theme=#{$theme}] > button {
          background: var(--theme-color-#{$theme}-default);
          border-color: var(--theme-color-#{$theme}-default);
          color: var(--text-brightness-rev-default);

          &:hover {
            background: var(--theme-color-#{$theme}-dark);
            border-color: var(--theme-color-#{$theme}-dark);
            color: var(--text-brightness-rev-default);
          }

          &:active {
            background: var(--theme-color-#{$theme}-darker);
            border-color: var(--theme-color-#{$theme}-darker);
            color: var(--text-brightness-rev-default);
          }

          &:disabled {
            background: var(--theme-color-grey-lighter);
            border-color: var(--theme-color-grey-lighter);
            color: var(--text-brightness-lighter);
            cursor: default;
          }
        }
      }

      &[sd-inline=true] > button {
        display: inline-block;
        width: auto;
        vertical-align: top;
      }

      &[sd-size=sm] > button {
        font-weight: normal;
        padding: var(--gap-xs) var(--gap-default);
      }

      &[sd-size=lg] > button {
        padding: var(--gap-default) var(--gap-xl);
        //border-radius: 2px;
      }
    }
  `]
})
export class SdButtonControl {
  @Input()
  @SdInputValidate({
    type: String,
    includes: ["primary", "secondary", "info", "success", "warning", "danger"]
  })
  @HostBinding("attr.sd-theme")
  public theme?: "primary" | "secondary" | "info" | "success" | "warning" | "danger";

  @Input()
  @SdInputValidate(Boolean)
  @HostBinding("attr.sd-inline")
  public inline?: boolean;

  @Input()
  @SdInputValidate({
    type: String,
    includes: ["sm", "lg"]
  })
  @HostBinding("attr.sd-size")
  public size?: "sm" | "lg";

  @Input()
  @SdInputValidate(Boolean)
  public disabled?: boolean;

  @Input("button.style")
  @SdInputValidate(String)
  public buttonStyle?: string;

  @Input("button.class")
  @SdInputValidate(String)
  public buttonClass?: string;

  @Input()
  @SdInputValidate({
    type: String,
    includes: ["button", "submit"],
    notnull: true
  })
  public type: "button" | "submit" = "button";

  @Input()
  @SdInputValidate(Boolean)
  @HostBinding("attr.sd-inset")
  public inset?: boolean;

  public constructor(private readonly _sanitization: DomSanitizer) {
  }

  public safeHtml(value?: string): SafeHtml | undefined {
    return value !== undefined ? this._sanitization.bypassSecurityTrustStyle(value) : undefined;
  }
}
