// _back/240919_react_포기/sd-react/src/controls/SdToast.tsx
import { component, TFwdRef, TProps } from "../utils/component";
import styled, { css, keyframes } from "styled-components";
import { omit } from "../utils/omit";
import { keys } from "@simplysm/ts-transformer-keys";
import { mixins } from "../style/mixins";
import { variables } from "../style/variables";

export type TSdToastTheme = "info" | "success" | "warning" | "danger";

interface IProps {
  $progress?: number;
  $theme?: TSdToastTheme;
  $closing?: boolean;
}

export const SdToast = component("SdToast", (props: TProps<IProps, "div">, fwdRef: TFwdRef<"div">) => {
  return (
    <RootDiv
      {...omit(props, keys<IProps>())}
      ref={fwdRef}
      $progress={props.$progress}
      $theme={props.$theme ?? "info"}
      $closing={props.$closing ?? false}
    >
      <div className={"_sd-toast-block"}>
        <div className={"_sd-toast-message"}>{props.children}</div>
        {props.$progress != null && (
          <div className={"_sd-toast-progress"}>
            <div className={"_sd-toast-progress-bar"}></div>
          </div>
        )}
      </div>
    </RootDiv>
  );
});

const RootDiv = styled.div<{
  $progress: number | undefined;
  $theme: TSdToastTheme;
  $closing: boolean;
}>`
  ${props => css`
    display: block;
    margin-bottom: var(--gap-sm);
    text-align: center;
    width: 100%;
    pointer-events: none;

    > ._sd-toast-block {
      display: inline-block;
      text-align: left;
      color: white;
      border-radius: var(--border-radius-lg);
      ${mixins.elevation(12)}
      pointer-events: auto;

      transform: none;
      opacity: 1;
      animation: ${kfOpen(false)} 0.1s ease-out;

      ${props.$closing && css`
        transform: translateY(-100%);
        transition: 0.1s ease-in;
        transition-property: transform, opacity;
        opacity: 0;
      `};

      > ._sd-toast-message {
        padding: var(--gap-default) var(--gap-lg);
      }

      ${props.$progress != null && css`
        > ._sd-toast-progress {
          background: var(--theme-grey-default);
          height: 4px;
          border-radius: var(--border-radius-xl);
          margin: 0 4px 4px 4px;

          > ._sd-toast-progress-bar {
            border-radius: var(--border-radius-xl);
            height: 4px;
            transition: width 1s ease-out;
            width: ${props.$progress}%;
          }
        }`
      }
    }

    ${Object.keys(variables.theme).map(
      (key) => css`
        > ._sd-toast-block {
          background: var(--theme-${key}-default);

          > ._sd-toast-progress {
            background: var(--theme-${key}-darker);

            > ._sd-toast-progress-bar {
              background: var(--theme-${key}-lighter);
            }
          }
        }
      `
    )};

    @media (max-width: 520px) {
      ${kfOpen(true)}
      > ._sd-toast-block {
        border-radius: calc(var(--line-height) / 2);

        > ._sd-toast-message {
          padding: var(--gap-xs) var(--gap-default);
        }
      }
    }
  `}
`;

const kfOpen = (bottom: boolean) => keyframes`
  from {
    transform: translateY(${bottom ? "100%" : "-100%"});
    opacity: 0;
  }
  to {
    transform: none;
    opacity: 1;
  }
`;

// packages/angular/src/ui/overlay/toast/sd-toast.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  model,
  ViewEncapsulation,
} from "@angular/core";
import type { SdToastTheme } from "../../../core/providers/sd-toast.provider";

const POLITE_THEMES: ReadonlySet<string> = new Set(["info", "success"]);
const ASSERTIVE_THEMES: ReadonlySet<string> = new Set(["warning", "danger"]);

@Component({
  selector: "sd-toast",
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  standalone: true,
  host: {
    "[attr.data-sd-open]": "open() || undefined",
    "[attr.data-sd-theme]": "theme()",
    "[attr.role]": "ariaRole()",
    "[attr.aria-live]": "ariaLive()",
  },
  template: `
    @if (message() !== undefined) {
      <div class="_message">{{ message() }}</div>
    }
    <ng-content />
    @if (useProgress()) {
      <div class="_progress">
        <div class="_progress-bar" [style.width.%]="progress()"></div>
      </div>
    }
  `,
  styles: [
    /* language=SCSS */ `
      @use "../../../../scss/commons/variables";
      @use "../../../../scss/commons/mixins";
      @use "sass:map";

      sd-toast {
        display: block;
        position: relative;
        max-width: 32.5rem;
        width: 100%;
        margin: var(--gap-sm);
        padding: var(--gap-default) var(--gap-lg);
        border-radius: var(--border-radius-default);
        color: var(--text-trans-rev-default);
        pointer-events: auto;
        transform: translateY(-100%);
        opacity: 0;
        transition:
          transform var(--animation-duration) ease,
          opacity var(--animation-duration) ease;

        @include mixins.elevation(12);

        &[data-sd-open] {
          transform: translateY(0);
          opacity: 1;
        }

        @each $theme-name, $theme-map in map.get(variables.$vars, theme) {
          &[data-sd-theme="#{$theme-name}"] {
            background: map.get($theme-map, default);
          }
        }

        > ._message {
          word-break: break-all;
          white-space: pre-wrap;
        }

        > ._progress {
          position: absolute;
          bottom: 0;
          left: 0;
          right: 0;
          height: 0.25rem;
          background: var(--trans-lighter);
          border-radius: 0 0 var(--border-radius-default) var(--border-radius-default);
          overflow: hidden;

          > ._progress-bar {
            height: 100%;
            background: var(--trans-default);
            transition: width 0.3s ease;
          }
        }

        @media all and (max-width: variables.$breakpoint-mobile) {
          max-width: none;
          margin: var(--gap-xs);
          border-radius: 0;
        }
      }
    `,
  ],
})
export class SdToast {
  open = model(false);
  useProgress = input(false, { transform: booleanAttribute });
  theme = input<SdToastTheme>("info");
  progress = model(0);
  message = model<string | undefined>(undefined);

  ariaRole = computed(() => {
    const t = this.theme();
    if (POLITE_THEMES.has(t)) return "status";
    if (ASSERTIVE_THEMES.has(t)) return "alert";
    return undefined;
  });

  ariaLive = computed(() => {
    const t = this.theme();
    if (POLITE_THEMES.has(t)) return "polite";
    if (ASSERTIVE_THEMES.has(t)) return "assertive";
    return undefined;
  });
}
