// packages/sd-react/src/controls/SdButton.tsx
import { ReactNode } from "react";
import styled, { css } from "styled-components";
import { styleProps, TStyleProps } from "../utils/styleProps";
import { mixins } from "../style/mixins";

interface IProps {
  type?: "button" | "submit";
  theme?:
    | "primary"
    | "secondary"
    | "info"
    | "success"
    | "warning"
    | "danger"
    | "grey"
    | "blue-grey"
    | "link"
    | "link-primary"
    | "link-secondary"
    | "link-info"
    | "link-success"
    | "link-warning"
    | "link-danger"
    | "link-grey"
    | "link-blue-grey";
  inline?: boolean;
  inset?: boolean;
  size?: "sm" | "lg";
  disabled?: boolean;

  onClick?: () => void;

  children?: ReactNode;
}

export default function SdButton(props: IProps) {
  return <Root {...styleProps(props)} onClick={props.onClick}>{props.children}</Root>;
}

const Root = styled.button<TStyleProps<Omit<IProps, "children" | "onClick">>>`
  ${(props) => [
    css`
      font-family: var(--font-family);

      display: block;
      width: 100%;
      padding: var(--gap-sm) var(--gap-lg);
      background: white;

      font-size: var(--font-size-default);
      line-height: var(--line-height);

      border-radius: ${props.$inset ? 0 : "var(--border-radius-default)"};
      border: ${props.$inset ? "none" : "1px solid var(--border-color-default)"};
      color: var(--text-trans-default);

      user-select: none;

      font-weight: bold;
      text-align: center;
      cursor: pointer;

      transition: background 0.1s linear;

      &:hover {
        background: var(--theme-grey-lightest);
        ${props.$inset &&
        css`
          color: var(--theme-primary-darker);
        `}
      }

      ${mixins.activeEffect(true)}
      &:disabled {
        background: white;
        border-color: var(--theme-grey-lighter);
        color: var(--text-trans-lighter);
        cursor: default;

        ${mixins.activeEffect(false)}
      },

      ${props.$theme &&
      !props.$theme.startsWith("link") &&
      css`
        background: var(--theme-${props.$theme}-default);
        border-color: var(--theme-${props.$theme}-default);
        color: var(--text-trans-rev-default);

        &:hover {
          background: var(--theme-${props.$theme}-dark);
          border-color: var(--theme-${props.$theme}-dark);
          color: var(--text-trans-rev-default);
        }

        &:disabled {
          background: var(--theme-grey-lighter);
          border-color: var(--theme-grey-lighter);
          color: var(--text-trans-lighter);
          cursor: default;
        }
      `}

      ${props.$theme === "link" &&
      css`
        border-color: transparent;
        color: var(--theme-primary-default);

        &:hover {
          color: var(--theme-primary-darker);
        }

        &:disabled {
          border-color: transparent;
          color: var(--text-trans-lighter);
        }
      `}

    ${props.$theme &&
      props.$theme.startsWith("link") &&
      css`
        border-color: transparent;
        color: var(--theme-${props.$theme.substring(5)}-default);

        &:hover {
          color: var(--theme-${props.$theme.substring(5)}-darker);
        }

        &:disabled {
          border-color: transparent;
          color: var(--text-trans-lighter);
        }
      `}

    ${props.$inline &&
      css`
        display: inline-block;
        width: auto;
        vertical-align: top;
      `}

    ${props.$size === "sm" &&
      css`
        padding: var(--gap-xs) var(--gap-default);
      `}

    ${props.$size === "lg" &&
      css`
        padding: var(--gap-default) var(--gap-xl);
      `}

    ${props.$disabled &&
      css`
        pointer-events: none;
      `}
    `,
  ]}
`;

// packages/sd-angular/src/modules/button/sd-button.component.ts
import { ChangeDetectionStrategy, Component, HostBinding, Input } from "@angular/core";
import { SdInputValidate } from "../../decorators/SdInputValidate";
import { sdThemes, TSdTheme } from "../../commons";

@Component({
  selector: "sd-button",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button tabindex="0"
            [attr.type]="type"
            [disabled]="disabled"
            [attr.class]="buttonClass"
            [attr.style]="buttonStyle">
      <ng-content></ng-content>
    </button>`,
  styles: [/* language=SCSS */ `
    @import "../../../scss/mixins";
    @import "../../../scss/variables-scss-arr";

    :host {
      > button {
        @include form-control-base();
        padding: var(--gap-sm) var(--gap-lg);

        background: white;
        border-color: var(--sd-border-color);
        border-radius: 2px;

        font-weight: bold;
        text-align: center;
        cursor: pointer;

        &:hover {
          background: var(--theme-color-grey-lightest);
        }

        &:active {
          background: var(--theme-color-grey-lighter);
        }

        &:disabled {
          background: white;
          border-color: var(--theme-color-grey-lighter);
          color: var(--text-brightness-lighter);
          cursor: default;
        }
      }

      &[sd-inset] > button {
        border-radius: 0;
        border: none;
        color: var(--theme-color-primary-default);

        &:hover {
          color: var(--theme-color-primary-darker);
        }

        &:disabled {
          background: white;
          border-color: var(--theme-color-grey-lighter);
          //color: var(--text-brightness-lighter);
          color: var(--text-brightness-default);
          cursor: default;
        }
      }

      @each $theme in $arr-theme-color {
        &[sd-theme=#{$theme}] > button {
          background: var(--theme-color-#{$theme}-default);
          border-color: var(--theme-color-#{$theme}-default);
          color: var(--text-brightness-rev-default);

          &:hover {
            background: var(--theme-color-#{$theme}-dark);
            border-color: var(--theme-color-#{$theme}-dark);
            color: var(--text-brightness-rev-default);
          }

          &:active {
            background: var(--theme-color-#{$theme}-darker);
            border-color: var(--theme-color-#{$theme}-darker);
            color: var(--text-brightness-rev-default);
          }

          &:disabled {
            background: var(--theme-color-grey-lighter);
            border-color: var(--theme-color-grey-lighter);
            color: var(--text-brightness-lighter);
            cursor: default;
          }
        }
      }

      &[sd-inline=true] > button {
        display: inline-block;
        width: auto;
        vertical-align: top;
      }

      &[sd-size=sm] > button {
        font-weight: normal;
        padding: var(--gap-xs) var(--gap-default);
      }

      &[sd-size=lg] > button {
        padding: var(--gap-default) var(--gap-xl);
        //border-radius: 2px;
      }

      &[disabled=true] {
        pointer-events: none;
      }
    }
  `]
})
export class SdButtonComponent {
  @Input()
  @SdInputValidate({
    type: String,
    includes: sdThemes
  })
  @HostBinding("attr.sd-theme")
  public theme?: TSdTheme;

  @Input()
  @SdInputValidate(Boolean)
  @HostBinding("attr.sd-inline")
  public inline?: boolean;

  @Input()
  @SdInputValidate({
    type: String,
    includes: ["sm", "lg"]
  })
  @HostBinding("attr.sd-size")
  public size?: "sm" | "lg";

  @Input()
  @SdInputValidate(Boolean)
  @HostBinding("attr.disabled")
  public disabled?: boolean;

  @Input("button.style")
  @SdInputValidate(String)
  public buttonStyle?: string;

  @Input("button.class")
  @SdInputValidate(String)
  public buttonClass?: string;

  @Input()
  @SdInputValidate({
    type: String,
    includes: ["button", "submit"],
    notnull: true
  })
  public type: "button" | "submit" = "button";

  @Input()
  @SdInputValidate(Boolean)
  @HostBinding("attr.sd-inset")
  public inset?: boolean;
}
