// packages/sd-vue/src/controls/SdButtonControl.vue
<template>
  <div class="sd-button"
       :sd-theme="theme"
       :sd-size="size"
       :sd-inline="inline"
       :sd-inset="inset"
       :sd-invalid="isInvalid"
       @click="onClick">
    <button :type="type" :disabled="disabled">
      <slot></slot>
    </button>
    <div class="_invalid-indicator"></div>
  </div>
</template>

<script lang="ts">
  import {Component, Emit, Prop, Vue} from "vue-property-decorator";

  @Component
  export default class SdButtonControl extends Vue {
    @Prop({
      type: String,
      validator: value => ["primary", "secondary", "info", "success", "warning", "danger"].includes(value)
    })
    public theme?: "primary" | "secondary" | "info" | "success" | "warning" | "danger";

    @Prop({
      type: String,
      validator: value => ["sm", "lg"].includes(value)
    })
    public size?: "sm" | "lg";

    @Prop({
      type: String,
      default: "button",
      validator: value => ["button", "submit"].includes(value)
    })
    public type!: "button" | "submit";

    @Prop(Boolean)
    public inline?: boolean;

    @Prop(Boolean)
    public required?: boolean;

    @Prop(Boolean)
    public disabled?: boolean;

    @Prop(Boolean)
    public inset?: boolean;

    @Emit()
    public click(event: MouseEvent): MouseEvent {
      return event;
    }

    public isInvalid = false;

    public onClick(event: MouseEvent): void {
      this.click(event);
    }

    public mounted(): void {
      this._refresh();
    }

    public updated(): void {
      this._refresh();
    }

    private _refresh(): void {
      this.isInvalid = this.required === true && !(this.$el.firstChild as HTMLElement).innerText.trim();
    }
  }
</script>

<style scoped lang="scss">
  @import "../scss/presets";

  .sd-button {
    display: block;
    position: relative;

    > button {
      @include form-control-base();

      font-weight: bold;
      background: white;
      cursor: pointer;
      color: var(--theme-primary-default);
      border-radius: 3px;

      &:hover {
        background: var(--theme-grey-lightest);
      }

      &:focus {
        outline-color: transparent;
        background: var(--theme-grey-lightest);
      }

      &:active {
        background: var(--theme-grey-lighter);
      }

      &:disabled {
        background: transparent;
        cursor: default;
        color: var(--text-color-default);
      }
    }

    @each $key, $val in map_get($root, theme) {
      &[sd-theme=#{$key}] > button {
        background: var(--theme-#{$key}-default);
        border-color: var(--theme-#{$key}-default);
        color: var(--text-reverse-color-default);

        &:hover,
        &:focus {
          background: var(--theme-#{$key}-dark);
          border-color: var(--theme-#{$key}-dark);
        }

        &:active {
          background: var(--theme-#{$key}-darker);
          border-color: var(--theme-#{$key}-darker);
        }

        &:disabled {
          background: var(--theme-grey-default);
          border-color: var(--theme-grey-default);
          cursor: default;
        }
      }
    }

    &[sd-size=sm] > button {
      padding: var(--gap-xs) var(--gap-sm);
    }

    &[sd-size=lg] > button {
      padding: var(--gap-default) var(--gap-lg);
    }

    &[sd-inline=true] {
      display: inline-block;

      > button {
        width: 100%;
      }
    }

    &[sd-invalid=true] > ._invalid-indicator {
      @include invalid-indicator();
    }

    &[sd-inset=true] {
      > button {
        border: none !important;
        box-shadow: none !important;
        border-radius: 0;
        color: var(--theme-primary-default);

        &:hover {
          background: var(--theme-grey-lightest);
        }

        &:active {
          background: var(--theme-grey-lighter);
        }

        &:disabled {
          background: transparent;
        }
      }

      @each $key, $val in map_get($root, theme) {
        &[sd-theme=#{$key}] > button {
          background: var(--theme-#{$key}-default);

          &:hover {
            background: var(--theme-#{$key}-dark);
          }

          &:active {
            background: var(--theme-#{$key}-darker);
          }

          &:disabled {
            background: var(--theme-grey-default);
          }
        }
      }
    }
  }
</style>

// packages/sd-angular/src/modules/button/SdButtonControl.ts
import {
  AfterContentChecked,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostBinding,
  Input,
  ViewEncapsulation
} from "@angular/core";
import {SdTypeValidate} from "../../commons/SdTypeValidate";

@Component({
  selector: "sd-button",
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <button [type]="type" [disabled]="disabled">
      <ng-content></ng-content>
    </button>
    <div class="_invalid-indicator"></div>`,
  styles: [/* language=SCSS */ `
    @import "../../../scss/presets";

    sd-button {
      display: block;
      position: relative;

      > button {
        @include form-control-base();

        font-weight: bold;
        background: white;
        cursor: pointer;
        color: var(--theme-primary-default);
        border-radius: 3px;

        &:hover {
          background: var(--theme-grey-lightest);
        }

        &:focus {
          outline-color: transparent;
          background: var(--theme-grey-lightest);
        }

        &:active {
          background: var(--theme-grey-lighter);
        }

        &:disabled {
          background: transparent;
          cursor: default;
          color: var(--text-color-default);
        }
      }

      @each $color in $arr-theme-color {
        &[sd-theme=#{$color}] > button {
          background: var(--theme-#{$color}-default);
          border-color: var(--theme-#{$color}-default);
          color: var(--text-reverse-color-default);

          &:hover,
          &:focus {
            background: var(--theme-#{$color}-dark);
            border-color: var(--theme-#{$color}-dark);
          }

          &:active {
            background: var(--theme-#{$color}-darker);
            border-color: var(--theme-#{$color}-darker);
          }

          &:disabled {
            background: var(--theme-grey-default);
            border-color: var(--theme-grey-default);
            cursor: default;
          }
        }
      }

      &[sd-size=sm] > button {
        padding: var(--gap-xs) var(--gap-sm);
      }

      &[sd-size=lg] > button {
        padding: var(--gap-default) var(--gap-lg);
      }

      &[sd-inline=true] {
        display: inline-block;

        > button {
          width: 100%;
        }
      }

      &[sd-invalid=true] > ._invalid-indicator {
        @include invalid-indicator();
      }

      &[sd-inset=true] {
        > button {
          border: none !important;
          box-shadow: none !important;
          border-radius: 0;
          color: var(--theme-primary-default);

          &:hover {
            background: var(--theme-grey-lightest);
          }

          &:active {
            background: var(--theme-grey-lighter);
          }

          &:disabled {
            background: transparent;
          }
        }

        @each $color in $arr-theme-color {
          &[sd-theme=#{$color}] > button {
            background: var(--theme-#{$color}-default);

            &:hover {
              background: var(--theme-#{$color}-dark);
            }

            &:active {
              background: var(--theme-#{$color}-darker);
            }

            &:disabled {
              background: var(--theme-grey-default);
            }
          }
        }
      }
    }
  `]
})
export class SdButtonControl implements AfterContentChecked {
  @Input()
  @SdTypeValidate({
    type: String,
    includes: ["primary", "secondary", "info", "success", "warning", "danger"]
  })
  @HostBinding("attr.sd-theme")
  public theme?: "primary" | "secondary" | "info" | "success" | "warning" | "danger";

  @Input()
  @SdTypeValidate({
    type: String,
    includes: ["sm", "lg"]
  })
  @HostBinding("attr.sd-size")
  public size?: "sm" | "lg";

  @Input()
  @SdTypeValidate({
    type: String,
    includes: ["button", "submit"],
    notnull: true
  })
  public type: "button" | "submit" = "button";

  @Input()
  @SdTypeValidate(Boolean)
  @HostBinding("attr.sd-inline")
  public inline?: boolean;

  @Input()
  @SdTypeValidate(Boolean)
  public required?: boolean;

  @Input()
  @SdTypeValidate(Boolean)
  public disabled?: boolean;

  @Input()
  @SdTypeValidate(Boolean)
  @HostBinding("attr.sd-inset")
  public inset?: boolean;

  @HostBinding("attr.sd-invalid")
  public isInvalid = false;

  public constructor(private readonly _elRef: ElementRef) {
  }

  public ngAfterContentChecked(): void {
    this.isInvalid = false;

    if (this.required) {
      if (!((this._elRef.nativeElement as HTMLElement).findAll("> button")[0] as HTMLElement).innerText.trim()) {
        this.isInvalid = true;
      }
    }
  }
}
