// packages/sd-vue/src/controls/SdCardControl.vue
<template>
  <div class="sd-card">
    <slot></slot>
  </div>
</template>

<script lang="ts">
  import {Component, Vue} from "vue-property-decorator";

  @Component
  export default class SdCardControl extends Vue {
  }
</script>

<style scoped lang="scss">
  @import "../scss/presets";

  .sd-card {
    display: block;
    background: white;
    border-radius: 2px;
    @include elevation(1);
    overflow: hidden;
  }
</style>

// packages/sd-angular/src/modules/card/SdCardControl.ts
import {ChangeDetectionStrategy, Component, ViewEncapsulation} from "@angular/core";

@Component({
  selector: "sd-card",
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <ng-content></ng-content>`,
  styles: [/* language=SCSS */ `
    @import "../../../scss/presets";

    sd-card {
      display: block;
      background: white;
      border-radius: 2px;
      @include elevation(1);
      overflow: hidden;
    }
  `]
})
export class SdCardControl {
}
