// packages/sd-vue/src/controls/SdCardControl.vue
<template>
  <div class="sd-card">
    <slot></slot>
  </div>
</template>

<script lang="ts">
  import {Component, Vue} from "vue-property-decorator";

  @Component
  export default class SdCardControl extends Vue {
  }
</script>

<style scoped lang="scss">
  @import "../scss/presets";

  .sd-card {
    display: block;
    background: white;
    border-radius: 2px;
    @include elevation(1);
    overflow: hidden;
  }
</style>

// _back/220820/sd-angular/src/controls/SdCardControl.ts
import { ChangeDetectionStrategy, Component, HostBinding, Input } from "@angular/core";
import { SdInputValidate } from "../decorators/SdInputValidate";

@Component({
  selector: "sd-card",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-content></ng-content>`,
  styles: [/* language=SCSS */ `
    @import "../../scss/scss_settings";

    :host {
      display: block;
      background: white;
      border-radius: var(--border-radius-xl);
      overflow: hidden;
      @include elevation(4);

      &[sd-elevation=none] {
        @include elevation(0);
      }
      
      &[sd-elevation=sm] {
        @include elevation(2);
      }

      &[sd-elevation=lg] {
        @include elevation(8);
      }

      &[sd-elevation=xl] {
        @include elevation(16);
      }
    }
  `]
})
export class SdCardControl {
  @Input()
  @SdInputValidate({ type: String, includes: ["none", "sm", "lg", "xl"] })
  @HostBinding("attr.sd-elevation")
  public elevation?: "none" | "sm" | "lg" | "xl";
}
